name: Release on Version Change

on:
  push:
    branches: [ main ]
    paths: ['pyproject.toml']

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install toml

    - name: Check for version change
      id: version_check
      run: |
        # Extract version from pyproject.toml
        version=$(python -c "import toml; print(toml.load('pyproject.toml')['tool']['poetry']['version'])")
        echo "Version=$version"
        echo "::set-output name=version::$version"

        # Check if this version tag already exists
        if git rev-parse "v$version" >/dev/null 2>&1; then
            echo "Version already released"
            echo "::set-output name=should_release::false"
        else
            echo "New version detected"
            echo "::set-output name=should_release::true"
        fi

    - name: Create Release
      if: steps.version_check.outputs.should_release == 'true'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version_check.outputs.version }}
        release_name: Release v${{ steps.version_check.outputs.version }}
        draft: false
        prerelease: false
