name: Lint Code and Run Tests
on:
  pull_request:
    branches: [ main ]
jobs:
  format-lint:
    uses: ./.github/actions/_format-lint-action.yml@main
    with:
      python-version: '3.9'
  test:
    needs: format-lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11']
    uses: ./.github/actions/_run-tests-action.yml@main
    with:
      runner-os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
  comment-coverage-report:
    needs: [ test ]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Download coverage report artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
      - name: Read coverage report
        id: read-coverage
        run: |
          echo "COVERAGE_REPORT<<EOF" >> $GITHUB_ENV
          cat coverage_report.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Comment coverage report
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Test Coverage Report
            ```
            ${{ env.COVERAGE_REPORT }}
            ```